name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Version

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fakeroot -y
      - name: Build .deb
        run: ./gradlew :ui:packageDeb
      - name: Build .rpm
        run: ./gradlew :ui:packageRpm
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: intervirt_linux
          path: |
            ui/build/compose/binaries/main/deb/*.deb
            ui/build/compose/binaries/main/rpm/*.rpm
          overwrite: true

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
      - name: Build .exe
        run: ./gradlew :ui:packageExe
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: intervirt_windows
          path: |
            ui/build/compose/binaries/main/exe/*.exe
          overwrite: true
